apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: todoapi
      context: TodoApi
    - image: todofrontend
      context: TodoFrontend

deploy:
  kubectl:
    manifests:
      - k8s/local/config.local.yml
      - k8s/local/todoapi-stable-service.yml
      - k8s/local/todoapi-canary-deployment.yml
      - k8s/local/todofrontend-service.yml


profiles:
  - name: cloud
    #build:
    #  artifacts:
    #    # Use "default-repo" to override the "gcr.io/PROJECT_ID/" prefix
    #    - image: gcr.io/PROJECT_ID/todoapi
    #      context: TodoApi
    #    - image: gcr.io/PROJECT_ID/todofrontend
    #      context: TodoFrontend
    deploy:
      kubectl:
        manifests:
          # Use "k8s/cloud/fix-name.py" to convert *.yml.tpl --> *.yml
          - k8s/cloud/config.cloud.yml
          - k8s/cloud/todoapi-stable-service.yml
          - k8s/cloud/todoapi-canary-deployment.yml
          - k8s/cloud/todofrontend-service.yml


